<?php

declare(strict_types=1);

namespace Tests\Cache;

use PHPUnit\Framework\TestCase;

abstract class AbstractTestCase extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        error_reporting(E_ALL ^ E_DEPRECATED);
        parent::setUpBeforeClass();
    }

    public static function markTestSkipped(string $message = ''): void
    {
        echo static::class;
        die("qweqweqw");
        parent::markTestSkipped($message); // TODO: Change the autogenerated stub
    }
}
