name: Checks

on: pull_request

jobs:
  composer-normalize:
    name: Composer Normalize
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 8.2
          coverage: none
          tools: composer-normalize

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Normalize
        run: |
          composer-normalize --dry-run
