name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

    services:
      redis:
        image: redis:6.0.0
        ports:
          - 6379:6379
      redis-cluster:
        image: grokzen/redis-cluster:7.0.10
        ports:
          - 7000:7000
          - 7001:7001
          - 7002:7002
        env:
          STANDALONE: 1
      memcached:
        image: memcached:1.6.5
        ports:
          - 11211:11211
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: pecl
          extensions: redis, memcached, mongodb, apcu, apc
          ini-values: apc.enable_cli=1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        env:
          PHP_VERSION: ${{ matrix.php }}
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: |
          ./vendor/bin/phpunit
